// <auto-generated/>
using System;
using System.Reflection;
using System.Resources;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

[assembly: InternalsVisibleTo("NameInProgress.Tests")]
[assembly: AssemblyCompany("k94ll13nn3")]
[assembly: AssemblyCopyright("Copyright © k94ll13nn3")]
[assembly: AssemblyProduct("NameInProgress")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]
[assembly: ComVisible(false)]
[assembly: CLSCompliant(false)]
#if DEBUG
[assembly: AssemblyConfiguration("Debug")]
#else
[assembly: AssemblyConfiguration("Release")]
#endif
